name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample to reproduce the issue
      render: swift
      placeholder: |
        let legoApi = LegoAPI(apiKey: "your-api-key")
        // Your code here

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform(s) are you seeing the problem on?
      multiple: true
      options:
        - iOS
        - macOS
        - Xcode Simulator
        - Device
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Rebrickable.framework are you running?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: xcode-version
    attributes:
      label: Xcode Version
      description: What version of Xcode are you using?
      placeholder: e.g., 15.4
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: iOS/macOS Version
      description: What version of iOS/macOS are you targeting?
      placeholder: e.g., iOS 17.5, macOS 14.5

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might help us understand the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true