name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      
    - name: Build Release Framework
      run: |
        swift build -c release
          
    - name: Run Tests
      run: |
        swift test
          
    - name: Generate Changelog
      id: changelog
      run: |
        # Get the tag name
        TAG_NAME=${GITHUB_REF#refs/tags/}
        
        # Get the previous tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        # Generate changelog
        if [ -n "$PREVIOUS_TAG" ]; then
          CHANGELOG=$(git log ${PREVIOUS_TAG}..HEAD --oneline --pretty=format:"- %s" | head -20)
        else
          CHANGELOG=$(git log --oneline --pretty=format:"- %s" | head -20)
        fi
        
        # Save changelog to output
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.changelog.outputs.TAG_NAME }}
        body: |
          ## Changes in ${{ steps.changelog.outputs.TAG_NAME }}
          
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Installation
          
          ### Swift Package Manager
          Add the following to your `Package.swift`:
          
          ```swift
          dependencies: [
              .package(url: "https://github.com/mpwg/Rebrickable.framework.git", from: "${{ steps.changelog.outputs.TAG_NAME }}")
          ]
          ```
          
          ### Xcode
          1. Go to File > Add Package Dependencies
          2. Enter: `https://github.com/mpwg/Rebrickable.framework.git`
          3. Select version: `${{ steps.changelog.outputs.TAG_NAME }}`
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
